DjangoDevelopmentTest/urls.py
from django.contrib import admin
# from DjangoUeditor import urls
from django.views.generic import RedirectView
from django.views.static import serve
from .settings import MEDIA_ROOT  # import MEDIA_ROOT from settings
from article import urls
from django.contrib import admin
from django.urls import path, include
from article import views
from webapp1 import views as mainView
from django.urls import re_path as url
from django.conf import settings
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', mainView.index),
    path('',mainView.index),
    path('login/',mainView.login),
    path('signup/',mainView.signUp),
    path('logout/',mainView.signout),
    path('article/', include('article.urls', namespace='article')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('ueditor/', include('DjangoUeditor.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.urls import re_path as url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

article/urls.py
from django.urls import re_path as url
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^$', views.article_list),
    # path used to import url to the view
    path('article-list/', views.article_list, name='article_list'),
    # article detail
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # delete article
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # create article
    path('create/', views.create, name='reate'),
    # update article
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

# the app name that is deploying
app_name = 'comment'

urlpatterns = [
    # leave comment that links to the article
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

article/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
# timezone used to deal with the work related with time
from django.utils import timezone
from django.urls import reverse

# blog article data model
class ArticlePost(models.Model):
    # article author, on_delete use to define the way to delete the data
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # article title
    title = models.CharField(max_length=100)

    # article body, textfield used to storage large amount of text data
    body = models.TextField()

    # article created time
    created = models.DateTimeField(default=timezone.now)

    # article last updated time
    updated = models.DateTimeField(auto_now=True)

    # article total views, default is 0
    total_views = models.PositiveIntegerField(default=0)

    # class Meta used to define metadata of the model
    class Meta:
        # ordering define the way sorting the data which the model return
        # '-created' define the most recent created article will be display on the top
        ordering = ('-created',)

    # __str__ define the retuen value when using str() function
    def __str__(self):
        # return self.title return the article title
        return self.title

        # get the article url
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

templates/base.html
<!--    载入静态文件-->
{% load static %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {{ content_form.media }}
    <!-- 预留网站标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="/static/img/皇冠.svg">
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.4.1-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/blog.css">
    <script type="text/javascript" src="/static/plugins/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap-3.4.1-dist/js/bootstrap.js"></script>
</head>

<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}
<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
<script src="{% static 'jquery/jquery-3.6.0.js' %}"></script>

<!--
    popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
    在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
    教程采用本地引入是为了让读者了解静态文件本地部署的流程。
-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
写文章
{% endblock title %}
{% block content %}

{% if user.is_authenticated %}
<div class="create">
    <form action="." method="post">
        {% csrf_token %}
        <div class="createForm">

            <!-- 标签 -->
            <label for="title">文章标题</label>
            <p></p>

            <!-- 文本框 -->
            <input type="text" class="form-control" id="title" name="title" style="width: 50%;">
            <p></p>

            <!-- 关键 -->
            <label for="body">文章内容</label>
            <p></p>
            <div class="uditor">{{ content_form }}</div>
           
            <!-- 关键 -->


        </div>
        <div>
            <p><span style="color:red;">{{ error_msg }}</span></p>
        </div>


        <button type="submit" class="saveButton">保存</button>
    </form>
</div>
{% else %}
<div class="page-header">
    <h1>用户未登录 </h1>
    <p>
    <h1><small>请登陆后进行操作</small></h1>
    </p>
</div>
{% endif %}

{% endblock content %}

templates/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
<div class="detail">
    <div class="container">
        <div class="row">
            <!-- 标题及作者 -->
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-primary">
                <a>作者：{{ article.author }}</a>
                <a>{{ article.created|date:'Y-m-d H:i:s' }}</a>
                <!-- 只有作者可以修改文章 -->
                {% if user == article.author %}
                · <a href="#" data-toggle="modal" data-target="#myModal">删除文章</a>
                · <a href="{% url "article:article_update" article.id %}">编辑文章</a>
                {% endif %}
                <small class="col align-self-end" style="color: gray;">
                    <span class="bi bi-eye">
                        {{ article.total_views }}
                    </span>
                </small>
            </div>
            <!-- 文章正文 -->
            <div class="col-12">
                <article>{{ article.body|safe }}</article>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="col-12">
            <!-- 发表评论 -->
            <hr>
            {% if user.is_authenticated %}
            <div>
                <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                我也要发言：
                            </strong>
                        </label>
                        <textarea type="text" class="form-control" id="body" name="body" rows="2">
                    </textarea>
                    </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">发送</button>
                </form>
            </div>
            <br>
            {% else %}
            <br>
            <h5 class="row justify-content-center">
                请<a href="/login/">登录</a>后回复
            </h5>
            <br>
            {% endif %}
        </div>
    </div>

    <div class="commentShow">
        <div class="container">
        <div class="col-12">
            <!-- 显示评论 -->
            <h5>共有{{ comments.count }}条评论</h5>
            <div>
                {% for comment in comments %}
                <hr>
                <p>
                    <!--        <strong style="color: pink">-->
                    <span class="bi bi-person" style="color: blue">
                        {{ comment.user }}
                    </span>
                    <!--        </strong> -->
                    于
                    <span style="color: green">
                        {{ comment.created|date:"Y-m-d H:i:s" }}
                    </span> 时说：
                </p>
                <pre style="font-family: inherit; font-size: 1em;">
    {{ comment.body }}</pre>
                {% endfor %}
            </div>
        </div>
    </div>
    


        <!-- 模态框 -->
        <div class="modal fade " id="myModal">
            <div class="modal-dialog modal-dialog-centered modal-sm">
                <div class="modal-content">
                    <!-- 模态框头部 -->
                    <div class="modal-header">
                        <h4 class="modal-title">确认删除</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <!-- 模态框主体 -->
                    <div class="modal-body">
                        确认删除文章？
                    </div>
                    <!-- 模态框底部 -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="confirm_delete()">
                            确定
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <script>
            // 删除文章的函数
            function confirm_delete() {
                location.href = '{% url "article:article_delete" article.id %}'
            }
        </script>

    </div>
</div>
{% endblock content %}

templates/footer.html
{% load static %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; LingyuWings 2023</p>
    </div>
</footer>

templates/header.html
<!-- 定义导航栏 -->
<div class="jumbotron">
    <div class="container">
        <h1 class="typeout">Personal Blog</h1>
        <p>Page of my persional website.</p>
    </div>
</div>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">主页</a></li>
                <li class="active"><a href="/article/">Blog<span class="sr-only">(current)</span></a></li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                        aria-expanded="false">功能列表<span class="caret"></span></a>

                    <ul class="dropdown-menu">
                        <li><a href="/article/create/">创建文章</a></li>
                        <!-- <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li> -->
                    </ul>
                {% else %}
                <li></li>
                {% endif %}

                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a>欢迎您：<em>{{ user.username }}</em><span>|</span></a></li>
                <li><a href="/logout/">退出</a></li>
                {% else %}
                <li><a href="/login/">登录</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

templates/index.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="shortcut icon" href="/static/img/皇冠.svg">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.4.1-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/index.css">
    <script type="text/javascript" src="/static/plugins/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap-3.4.1-dist/js/bootstrap.js"></script>
</head>

<body>
    <div class="con1">
        <div class="jumbotron">
            <div class="container">
                <h1 class="typeout">Hello, world!</h1>
                <p>Welcome to LingyuWings' personal website</p>
            </div>
        </div>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand"></a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">主页<span class="sr-only">(current)</span></a></li>
                        <li><a href="/article/">Blog</a></li>
                        <!-- <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                aria-expanded="false">Dropdown <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li> -->
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li><a>欢迎您：<em>{{ user.username }}</em><span>|</span></a></li>
                        <li><a href="/logout/">退出</a></li>
                        {% else %}
                        <li><a href="/login/">登录</a></li>
                        {% endif %}
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <!-- <div class="content">
            <div>
                <div class="page-header">
                    <h1>个人主页</h1>
                    <p>
                    <h1><small>页面介绍</small></h1>
                    </p>
                </div>
                <div class="page-content">
                    

                </div>
                <div class="page-header">
                    <h1>About me</h1>
                </div>
                <div class="page-content">
                    <p></p>
                    
                </div>
                <div class="page-header">
                    <h1>链接</h1>
                </div>
                <div class="page-content">
                    <p>
                        以下为该页面的github相关链接
                    </p>
                    <div class="gitAddress">
                        <iframe
                            src="https://ghbtns.com/github-btn.html?user=LingYuWings&repo=DjangoWebsite&type=watch&count=true&v=2"
                            frameborder="0" scrolling="0" width="150" height="20" title="GitHub"></iframe>
                        <iframe
                            src="https://ghbtns.com/github-btn.html?user=LingYuWings&repo=DjangoWebsite&type=fork&count=true"
                            frameborder="0" scrolling="0" width="150" height="20" title="GitHub"></iframe>
                        <iframe
                            src="https://ghbtns.com/github-btn.html?user=LingYuWings&repo=DjangoWebsite&type=star&count=true"
                            frameborder="0" scrolling="0" width="150" height="20" title="GitHub"></iframe>
                    </div>
                    <p>以下为一些个人联系方式：</p>
                    
                </div>
                
            </div>

        </div>
    </div> -->
    <div>
        <br><br><br>
    </div>
    <footer class="py-3 bg-dark fixed-bottom">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; LingyuWings 2023</p>
        </div>
    </footer>
</body>


</html>

templates/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 定义放置文章标题的div容器 -->
<div class="blogBody">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}">
                        最新
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?order=total_views">
                        最热
                    </a>
                </li>
            </ol>
        </nav>

        {% for article in articles %}
        <div class="page-header">
            <h1>{{ article.title }}</h1>
            <p>
            {{ article.body|slice:'20'|safe }}...
            </p>
            <p><a href="{% url 'article:article_detail' article.id %}" class="card-link">阅读本文</a></p>
            
            <small class="col align-self-end" style="color: gray;">
                <span class="bi bi-eye">
                    {{ article.total_views }}
                </span>
            </small>
        </div>  
        {% endfor %}
    </div>

    <!-- 页码导航 -->
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                <!-- 如果不是第一页，则显示上翻按钮 -->
                {% if articles.has_previous %}
                <!--                <a href="?page=1" class="btn btn-success">-->
                <!--                    &laquo; 1-->
                <!--                </a>-->
                <a href="?page=1&order={{ order }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}" class="btn btn-secondary">
                    {{ articles.previous_page_number }}
                </a>
                {% endif %}

                <!-- 当前页面 -->
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>

                <!-- 如果不是最末页，则显示下翻按钮 -->
                {% if articles.has_next %}
                <!--                <a href="?page={{ articles.next_page_number }}"-->
                <!--                   class="btn btn-secondary"-->
                <!--                >-->
                <!--                    {{ articles.next_page_number }}-->
                <!--                </a>-->
                <a href="?page={{ articles.next_page_number }}&order={{ order }}" class="btn btn-secondary">
                    {{ articles.next_page_number }}</a>
                <span>...</span>
                <!--                <a href="?page={{ articles.paginator.num_pages }}"-->
                <!--                   class="btn btn-success"-->
                <!--                >-->
                <!--                    {{ articles.paginator.num_pages }} &raquo;-->
                <!--                </a>-->
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}" class="btn btn-success">
                    {{ articles.paginator.num_pages }} &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% endblock content %}

templates/login.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <title>index</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="../static/plugins/bootstrap-3.4.1-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../static/css/login.css">
    <script type="text/javascript" src="../static/plugins/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="../static/plugins/bootstrap-3.4.1-dist/js/bootstrap.js"></script>
</head>

<body>
    <div class="login-form">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
              <div class="col-sm-10">
                <input name="username" class="form-control" id="username" placeholder="Username" required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
              <div class="col-sm-10">
                <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
              </div>
            </div>
            <div>
              <p><span style="color:red;">{{ error_msg }}</span></p>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-login">Login</button>
              </div>
            </div>
            <p>
              don't have an account? <a href="/signup">Sign up.</a>
            </p>
          </form>
    </div>
</body>

</html>

templates/signup.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <title>index</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="../static/plugins/bootstrap-3.4.1-dist/css/bootstrap.css">
    <link rel="stylesheet" href="../static/css/login.css">
    <script type="text/javascript" src="../static/plugins/jquery-3.6.3.js"></script>
    <script type="text/javascript" src="../static/plugins/bootstrap-3.4.1-dist/js/bootstrap.js"></script>
</head>

<body>
    <div class="login-form">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                  <input type="username" name="username" class="form-control" id="inputEmail3" placeholder="Username" required>
                </div>
              </div>
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
              <div class="col-sm-10">
                <input type="email" name="email" class="form-control" id="inputEmail3" placeholder="Email" required>
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
              <div class="col-sm-10">
                <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password" required>
              </div>
            </div>
            
            <div class="form-group">
              <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-login">SignUp</button>
              </div>
            </div>
            <p>
              Already have an account? <a href="/login">Log in.</a>
            </p>
          </form>
    </div>
    <div></div>
</body>

</html>

templates/update.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
修改文章
{% endblock title %}
{% block content %}

{% if user.is_authenticated %}
<div class="create">
    <form action="." method="post">
        {% csrf_token %}
        <div class="createForm">

            <!-- 标签 -->
            <label for="title">文章标题</label>
            <p></p>

            <!-- 文本框 -->
            <input type="text" class="form-control" id="title" name="title" style="width: 50%;">
            <p></p>

            <!-- 关键 -->
            <label for="id_body">文章内容</label>
            <p></p>
            <div class="uditor">{{ content_form }}</div>
           
            <!-- 关键 -->


        </div>
        <div>
            <p><span style="color:red;">{{ error_msg }}</span></p>
        </div>


        <button type="submit" class="saveButton">保存</button>
    </form>
</div>                
<script>
    {% if article %}
        //如果文章有内容就填充在content_form中
        document.getElementById("title").value='{{ article.title }}';

    {% endif %}
</script>
<script>
    {% if article %}
        document.getElementById("id_body").value='{{ article.body|safe }}';
    {% endif %}
</script>

{% else %}
<div class="page-header">
    <h1>用户未登录 </h1>
    <p>
    <h1><small>请登陆后进行操作</small></h1>
    </p>
</div>
{% endif %}

    

{% endblock content %}